// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("BarChart");

function make(id, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */(function () {
              var dt = new google.visualization.DataTable();
              dt.addColumn("string", "callstack");
              dt.addColumn("number", "count");
              dt.addRows(/* array */[
                    /* tuple */[
                      "city",
                      2010
                    ],
                    /* tuple */[
                      "city",
                      2011
                    ],
                    /* tuple */[
                      "city",
                      2013
                    ],
                    /* tuple */[
                      "city",
                      2014
                    ],
                    /* tuple */[
                      "city",
                      2015
                    ]
                  ]);
              var node = document.getElementById(id);
              var __x = new google.charts.Bar(node);
              __x.draw(dt, {
                    bars: "horizontal"
                  });
              return /* () */0;
            }),
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          id: id
                        });
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
