// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/lib/js/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var BarChart$BsGoogleCharts = require("./BarChart.bs.js");
var Component1$BsGoogleCharts = require("./Component1.bs.js");
var Script$BsReactScriptLoader = require("bs-react-script-loader/lib/js/src/Script.bs.js");
var PackageLoader$BsGoogleCharts = require("./PackageLoader.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component1$BsGoogleCharts.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Script$BsReactScriptLoader.make("https://www.gstatic.com/charts/loader.js", (function (remote) {
                switch (remote) {
                  case 0 : 
                      return "not asked";
                  case 1 : 
                      return "loading";
                  case 2 : 
                      return ReasonReact.element(/* None */0, /* None */0, PackageLoader$BsGoogleCharts.make(/* Upcoming */-162577412, /* :: */[
                                      /* Corechart */777774847,
                                      /* :: */[
                                        /* Bar */3303859,
                                        /* [] */0
                                      ]
                                    ], (function (remote$prime) {
                                        if (remote$prime) {
                                          return ReasonReact.element(/* None */0, /* None */0, BarChart$BsGoogleCharts.make("my-cool-chart", /* array */[]));
                                        } else {
                                          return "loading";
                                        }
                                      })));
                  case 3 : 
                      return "failure";
                  
                }
              }))), "index2");

/*  Not a pure module */
